### Muschrooms Dataset
Mushroom [Dataset]. (1981). UCI Machine Learning Repository. doi.org/10.24432/C5959T.

In [6]:
import pandas as pd
from coolcat import Coolcat

df = pd.read_csv('agaricus-lepiota.csv', sep=';')
df_class = df['class']
df.drop('class', axis=1, inplace=True)
for c in df.columns:
    df[c] = df[c].fillna(df[c].mode()[0])

df.head()

   1  2  3  4  5  6  7  8  9 10  ... 13 14 15 16 17 18 19 20 21 22
0  x  s  n  t  p  f  c  n  k  e  ...  s  w  w  p  w  o  p  k  s  u
1  x  s  y  t  a  f  c  b  k  e  ...  s  w  w  p  w  o  p  n  n  g
2  b  s  w  t  l  f  c  b  n  e  ...  s  w  w  p  w  o  p  n  n  m
3  x  y  w  t  p  f  c  n  n  e  ...  s  w  w  p  w  o  p  k  s  u
4  x  s  g  f  n  f  w  b  k  t  ...  s  w  w  p  w  o  e  n  a  g

[5 rows x 22 columns]

In [7]:
x=Coolcat(21)
labels = x.fit_predict(df)

In [8]:
df['class'] = df_class
df['labels'] = labels

result = df.groupby(['labels', 'class']).size().unstack(fill_value=0)
result = result[['p', 'e']] if 'p' in result.columns and 'e' in result.columns else result

In [9]:
result

class      p     e
labels
0        288     0
1         15    43
2          0   192
3          0   768
4        256     0
5          1   287
6       1296     0
7          0    48
8          0    78
9         71     1
10         0  1728
11         1    48
12         0    97
13        32    48
14        35   196
15         0   438
16         1   188
17       256     0
18       192     0
19      1472     0
20         0    48